/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.VentanaUsuarioControlador;
import Modelo.ConexionOracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus Trejo
 */
public class VentanaMenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuUsuario
     */
    
    
    public VentanaMenuUsuario() throws SQLException {
        initComponents();
        VentanaUsuarioControlador.initOutlets(Combo);
        VentanaUsuarioControlador.LlenarComboBoxSQL();
        PASS1.setEnabled(false);
        PASS2.setEnabled(false);
        BTNRegistrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LBLTitulo = new javax.swing.JLabel();
        LBLUsuario = new javax.swing.JLabel();
        LBLPass1 = new javax.swing.JLabel();
        LBLPass2 = new javax.swing.JLabel();
        TXTUsuario = new javax.swing.JTextField();
        PASS1 = new javax.swing.JPasswordField();
        PASS2 = new javax.swing.JPasswordField();
        LBLRol = new javax.swing.JLabel();
        Combo = new javax.swing.JComboBox();
        LBLRol1 = new javax.swing.JLabel();
        LBLRol2 = new javax.swing.JLabel();
        BTNROL = new javax.swing.JButton();
        BTNVolver = new javax.swing.JButton();
        BTNRegistrar = new javax.swing.JButton();
        BTNVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LBLTitulo.setText("Registro De Usuario");

        LBLUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLUsuario.setText("Nombre De usuario");

        LBLPass1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLPass1.setText("Contraseña");

        LBLPass2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLPass2.setText("Repita la Contraseña");

        TXTUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TXTUsuario.setText("jTextField1");

        PASS1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PASS1.setText("1");
        PASS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASS1ActionPerformed(evt);
            }
        });

        PASS2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PASS2.setText("1");

        LBLRol.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLRol.setText("Seleccione el rol que desea que tenga el usuario");

        Combo.setEditable(true);
        Combo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        LBLRol1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLRol1.setText("Si el rol deseado no se encuentra en la lista, puede ");

        LBLRol2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLRol2.setText("Crear un rol si es de su agrado");

        BTNROL.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BTNROL.setText("Crear Rol");
        BTNROL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNROLActionPerformed(evt);
            }
        });

        BTNVolver.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BTNVolver.setText("Volver");
        BTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverActionPerformed(evt);
            }
        });

        BTNRegistrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BTNRegistrar.setText("Registrar Usuario");
        BTNRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegistrarActionPerformed(evt);
            }
        });

        BTNVerificar.setFont(new java.awt.Font("Comic Sans MS", 2, 10)); // NOI18N
        BTNVerificar.setText("Verificar Usuario");
        BTNVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LBLUsuario)
                                .addGap(243, 243, 243))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBLPass1)
                                .addGap(270, 270, 270))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNVerificar)
                                .addGap(79, 79, 79)))
                        .addComponent(LBLRol)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LBLPass2)
                                .addGap(18, 18, 18)
                                .addComponent(PASS2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PASS1)
                                    .addComponent(TXTUsuario))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNRegistrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(LBLRol2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNROL)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLRol1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(LBLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(BTNVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LBLTitulo)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLUsuario)
                    .addComponent(TXTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLRol))
                .addGap(15, 15, 15)
                .addComponent(BTNVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPass1)
                    .addComponent(PASS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(LBLRol1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLRol2)
                            .addComponent(BTNROL))
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLPass2)
                            .addComponent(PASS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNVolver)
                            .addComponent(BTNRegistrar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BTNVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVerificarActionPerformed

        try{
            boolean disponible = VentanaUsuarioControlador.CompruebaUsuarioDisponibleSQL(TXTUsuario.getText());
            if (disponible){
                JOptionPane.showMessageDialog(rootPane,"EL USUARIO "+TXTUsuario.getText()+" SE ENCUENTRA DISPONIBLE");
                TXTUsuario.setEditable(false);
                BTNVerificar.setEnabled(false);
                PASS1.setEnabled(true);
                PASS2.setEnabled(true);
                BTNRegistrar.setEnabled(true);
            }
            else
                JOptionPane.showMessageDialog(rootPane,"ERROR, EL USUARIO "+TXTUsuario.getText()+" NO SE ENCUENTRA DISPONIBLE");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"ERROR, DEBE INGRESAR ALGUN USUARIO");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVerificarActionPerformed

    private void BTNROLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNROLActionPerformed
        try {
            VentanaMenuRoles Auxiliar = new VentanaMenuRoles();
            Auxiliar.setVisible(true);
            this.dispose();
            
           
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNROLActionPerformed

    private void BTNRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistrarActionPerformed

         try{
            if (PASS1.getText().equals(PASS2.getText())){
                String UsuarioSQL = TXTUsuario.getText();
                String PassSQL = PASS2.getText();
                //int rol = Combo.getSelectedIndex();
                //JOptionPane.showMessageDialog(rootPane,"EL ROL DEBERIA SER 1 PERO ES -> "+Integer.toHexString(rol));
                String rol = (String) Combo.getSelectedItem();
                //JOptionPane.showMessageDialog(rootPane,"EL ROL  ES -> "+pba);
                String rol2 = rol;
                VentanaUsuarioControlador.InsertaUsuarioBD(UsuarioSQL,PassSQL,rol2);
                JOptionPane.showMessageDialog(rootPane,"USUARIO CREADO CORRECTAMENTE");
                VentanaMenuPrincipal nuevo = new VentanaMenuPrincipal();
                nuevo.setVisible(true);
                this.dispose();
                
                
                
            }
            else{
            JOptionPane.showMessageDialog(rootPane,"ERROR, las contraseñas no coinciden.");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"ERROR, CONSULTA SQL. EN ->"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNRegistrarActionPerformed

    private void PASS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASS1ActionPerformed

    private void BTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverActionPerformed

         VentanaMenuUsuario nuevo = null;
        try {
            nuevo = new VentanaMenuUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
         nuevo.setVisible(true);
         this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaMenuUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaMenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNROL;
    private javax.swing.JButton BTNRegistrar;
    private javax.swing.JButton BTNVerificar;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JComboBox Combo;
    private javax.swing.JLabel LBLPass1;
    private javax.swing.JLabel LBLPass2;
    private javax.swing.JLabel LBLRol;
    private javax.swing.JLabel LBLRol1;
    private javax.swing.JLabel LBLRol2;
    private javax.swing.JLabel LBLTitulo;
    private javax.swing.JLabel LBLUsuario;
    private javax.swing.JPasswordField PASS1;
    private javax.swing.JPasswordField PASS2;
    private javax.swing.JTextField TXTUsuario;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
